language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN slug=sfr editor=cozy space=cozy_ccc
  - secure: M6X9PKSjBt9qXU+vp8Ww9Dsc8ZFNB5XXgi7CdHWleqhObadadO9DsmO6vEv6S2YENE0LrLafSkjjiDUACMTLGDN6wL6HtMER6GnrCshCg7kk1J2N5I9TFIUTiVqPZOY76rDaYZ7HdMiQIRupi600axEqNcRrZ2ujEfmn61ORkh2GYWERl2KImRGZDRL9At2S7F8Jy0Fb83tsh5p00hq0Jx4n6RMeow+bep0C7hxpUdV6O0a5vrc0Wqcr5BXkbkcfAnua1FVYDwU5UPck8CvbXrv1PyKqezKSTgyh8ydYztHDOf+t6EbotW89qujSehGeOCqpTBJB0VgYuvNuY31Uki5g9SfLwp1XNMbs9/3ruEoSIMyT39G4Zr1RjB2oOd7NT/091XnETMyi5a/BPPLiQPF42l43Lr9Sf7L++L3YPmvWHNA4uBpPyrPo+6FrhBrc8e0A8kP51ANeUk8cMvVWp3fQkiAox9LnEwzJT+X/8LXujHludszW9rJQW3fnZoNWRzm0yc0ES7NfSXkXOLRuKucD8R71ARVtvgkUV5zKBq5I+xikF9eax4GVbBy4/ZQdIO+H8Q/YexRpIwRMpEo4PYUJ8kogfeX3G6oaocYACR7IcQbHDkt8glMPHKj/EuX3vCgR6wqOmhq13mXjq4tlWCPHgVUcGl80JNcIc6b54k4=
  # MATTERMOST_HOOK_URL
  - secure: MKB2P0a0QiWek3Z06GPyIUschXi6rrVdJVkgQyeHe2RyzvJR2VVaP4p/5vDUJhGBh3bcAl8rgCGx4u8KlMtg706didaubnRCY7fxH0pmkLXYZOe785frHxKwuk2bFPOsbB8UyxDF3jh4a54RrJUcpiGp5rhMgbc+Z1shOOPI803ZZG0ysAJB43sZVRwrLNBTn9Risa3q1snWW+2EFqz/x3hMjp9w3WKQN2YPjSfwy6xfBXtUAUpjEG8bVSKZiN/6EbnD8VjV4ZdysVqHmnXuBuSSeVDc+wPPeofmsjA1UrivIK/Agj5YQq1KZ/HgvhJlUs0JIvcIDMJS7QtJF7Sr0Tm0rAg95Oc1BCCqvJWKzWWVAQk6tpK8Rj1lbLLS3fu7OXxcSiXxQo5hnPegPd8Mq28TfxCvtArNVh51YTrdh3OcP0j6K6daJxgPoMPuvFJzBKeGrr60TqZp3ERxX8Uar+IldgTB+hqvCEwCeGGfJA4OKwUHSo1iZgGuucsJcS4TiYwP4gL6yLVSe+URVM0Szcc59CHRezIy6EevaxSAtWpc/oAY4O88df1NokWo1d8b0FaE/LQ1BXjYmCw3U5tFOE/nYdt+30M6M849PrB/TKn1SIwxuk117P71cpL6dnVqDluIibh8uA436m9CnOdqJsbI3KDOJwPlGgH1maofVto=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
